version: "3.8"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  orchestrator:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - LLM_SERVICE_URL=http://llm-service:8001
      - RETRIEVAL_SERVICE_URL=http://retrieval-service:8002
      - ENVIRONMENT=development
    depends_on:
      redis:
        condition: service_healthy
      llm-service:
        condition: service_started
      retrieval-service:
        condition: service_started
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    command: uvicorn src.orchestrator.main:app --host 0.0.0.0 --port 8000 --reload

  llm-service:
    build: .
    ports:
      - "8001:8001"
    environment:
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=development
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    command: uvicorn src.llm_service.main:app --host 0.0.0.0 --port 8001 --reload

  retrieval-service:
    build: .
    ports:
      - "8002:8002"
    environment:
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=development
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    command: uvicorn src.retrieval_service.main:app --host 0.0.0.0 --port 8002 --reload

volumes:
  redis_data:
